version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: epr
      POSTGRES_USER: epr
      POSTGRES_PASSWORD: epr
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  api:
    build: .
    command: sh -c "python src/jobs/scheduler.py & uvicorn src.app.main:app --host 0.0.0.0 --port 8000"
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
